In [1]:
import numpy as np
import pandas as pd
import yfinance as yf
import sys
import os

# Add the utils folder to the path
sys.path.append(os.path.abspath("../utils"))

from quant_functions import (
    compute_log_returns,
    portfolio_return,
    portfolio_std,
    random_portfolio_performance,
    global_min_variance,
    max_sharpe_ratio,
    efficient_frontier,
    plot_efficient_frontier
)


In [3]:
data = yf.download(tickers, start="2020-01-01", auto_adjust=True)
prices = data["Close"]
prices.tail()

[*********************100%***********************]  4 of 4 completed


Ticker            AAPL        AMZN       GOOGL        MSFT
Date                                                      
2025-11-21  271.489990  220.690002  299.660004  472.119995
2025-11-24  275.920013  226.279999  318.579987  474.000000
2025-11-25  276.970001  229.669998  323.440002  476.989990
2025-11-26  277.549988  229.160004  319.950012  485.500000
2025-11-28  278.850006  233.220001  320.179993  492.010010

In [4]:
returns = compute_log_returns(prices)
returns.tail()

Ticker          AAPL      AMZN     GOOGL      MSFT
Date                                              
2025-11-21  0.019490  0.016217  0.034666 -0.013277
2025-11-24  0.016186  0.025014  0.061225  0.003974
2025-11-25  0.003798  0.014870  0.015140  0.006288
2025-11-26  0.002092 -0.002223 -0.010849  0.017684
2025-11-28  0.004673  0.017562  0.000719  0.013320

In [5]:
plot_efficient_frontier(returns)

DCPError: Problem does not follow DCP rules. Specifically:
The objective is not DCP. Its following subexpressions are not:
power(QuadForm(var31, [[0.10 0.07 0.07 0.07]
 [0.07 0.13 0.07 0.07]
 [0.07 0.07 0.11 0.07]
 [0.07 0.07 0.07 0.09]]), 0.5)